// Generated by CoffeeScript 1.9.0
(function() {
  casper.test.begin("Google's page testing!", 5, function(test) {
    casper.start("http://www.google.com/", function() {
      test.assertTitle("Google", "google homepage title is the one expected");
      test.assertExists('form[action="/search"]', "main form is found");
      return this.fill('form[action="/search"]', {
        q: "casperjs"
      }, true);
    });
    casper.then(function() {
      test.assertTitle("casperjs - Google 検索", "google title is ok");
      test.assertUrlMatch(/q=casperjs/, "search term has been submitted");
      return test.assertEval(function() {
        return __utils__.findAll("h3.r").length >= 10;
      }, "google search for \"casperjs\" retrieves 10 or more results");
    });
    return casper.run(function() {
      return test.done();
    });
  });

}).call(this);

//# sourceMappingURL=todoTest.js.map
