// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';

  /*
   * @ngdoc function
   * @name todomvcApp.controller:MainCtrl
   * @description
   * # MainCtrl
   * Controller of the todomvcApp
   */
  angular.module('todomvcApp').controller('MainCtrl', function($scope) {
    return $scope.awesomeThings = ['HTML5 Boilerplate', 'AngularJS', 'Karma'];
  });

}).call(this);

//# sourceMappingURL=main.js.map
