// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';

  /**
    * @ngdoc function
    * @name todomvcApp.controller:TodoCtrl
    * @description
    * # TodoCtrl
    * Controller of the Todoページ用のコントローラ
   */
  angular.module('todomvcApp').controller('TodoCtrl', function($scope, todoService) {
    var vm;
    return vm = this;
  });

}).call(this);

//# sourceMappingURL=todoCtrl.js.map
