// Generated by CoffeeScript 1.9.0
(function() {
  casper.addTodo = function(todo) {
    this.fillSelectors('.todo-form-input-wrapper', {
      'input.todo-form-input': todo
    });
    return this.sendKeys('input.todo-form-input', this.page.event.key.Enter, {
      keepFocus: true
    });
  };

  casper.captureEvidence = function(fileName) {
    return this.capture(this.global.evidenceFolder + "/" + fileName + ".png");
  };

}).call(this);

//# sourceMappingURL=inc.js.map
