// Generated by CoffeeScript 1.9.0
(function() {
  casper.echo("-- E2Eテスト(CasperJS)[開始] --");

  casper.global = {};

  casper.global.targetUrl = 'http://localhost:9000/';

  casper.test.done();

}).call(this);

//# sourceMappingURL=pre.js.map
