// Generated by CoffeeScript 1.9.0
(function() {
  casper.test.begin("TODOの追加テスト", 7, function(test) {
    casper.start(casper.global.targetUrl, function() {});
    casper.then(function() {
      test.info("タスクを１つ追加したら");
      this.addTodo('Go to buy a iMac');
      return this.waitForSelector('.todo-list-item .todo-list-task', function() {
        test.assertVisible('.todo-form-down-arrow', '矢印マークが表示されていること');
        test.assertExists('.todo-list-item .todo-form-check', 'チェックマークが表示されていること');
        test.assertElementCount('.todo-list-item', 1, 'ひとつのTODOタスクが表示されていること');
        test.assertSelectorHasText('.todo-list-item .todo-list-task', 'Go to buy a iMac', 'TODOタスクの中身が表示されていること');
        test.assertNotVisible('.todo-list-item .todo-form-remove', '削除マークが表示されていないこと');
        return test.assertSelectorHasText('.todo-form-footer .footer-left', '1 items left', 'アイテム数の表示が1となっていること');
      });
    });
    casper.then(function() {
      test.info("タスクにホバーしたら");
      this.mouse.move('.todo-list-item .todo-list-task');
      return this.waitForSelector('.todo-list-item .todo-form-remove', function() {
        return test.assertVisible('.todo-list-item .todo-form-remove', '削除マークが表示されていること');
      });
    });
    return casper.run(function() {
      return test.done();
    });
  });

}).call(this);

//# sourceMappingURL=2_addTodoTest.js.map
