// Generated by CoffeeScript 1.9.0
(function() {
  casper.test.begin("TodoMVCApp page testing!", 3, function(test) {
    casper.start(casper.global.targetUrl, function() {
      test.assertTitle("TodoMVC", "todoMVC App's title is TodoMVC");
      test.assertSelectorHasText('.header .header-title', 'todos', 'header text is \'todos\'');
      return test.assertSelectorHasText('.todo-form-footer .footer-left', '0 items left', 'item count is 0 when page shown');
    });
    return casper.run(function() {
      return test.done();
    });
  });

}).call(this);

//# sourceMappingURL=todoTest.js.map
