// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';

  /**
    * @ngdoc service
    * @name todomvcApp.todoService
    * @description
    * # todoService
    * Singletonなtodo機能のインスタンスを提供するFactoryです。
   */
  angular.module('todomvcApp').factory('todoService', function($filter, Todo) {
    var todoService;
    todoService = {
      todos: [],
      addTodo: function(task) {
        return this.todos.push(new Todo(task));
      },
      removeTodo: function(todo) {
        return this.todos = _.without(this.todos, todo);
      },
      getCompleted: function() {
        return $filter('filter')(this.todos, {
          isCompleted: true
        });
      },
      isAllCompleted: function() {
        return _.every(this.todos, function(todo) {
          return todo.isCompleted;
        });
      },
      asAllCompleted: function() {
        return _.map(this.todos, function(todo) {
          todo.isCompleted = true;
          return todo;
        });
      },
      toggleAllCompleted: function() {
        if (this.isAllCompleted()) {
          return _.map(this.todos, function(todo) {
            todo.isCompleted = !todo.isCompleted;
            return todo;
          });
        } else {
          return this.asAllCompleted();
        }
      },
      getNotCompleted: function() {
        return $filter('filter')(this.todos, {
          isCompleted: false
        });
      },
      clearCompleted: function() {
        return this.todos = _.reject(this.todos, function(todo) {
          return todo.isCompleted;
        });
      }
    };
    return todoService;
  });

}).call(this);

//# sourceMappingURL=todoService.js.map
