// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';

  /*
   * @ngdoc overview
   * @name todomvcApp
   * @description
   * # todomvcApp
   *
   * TodoMVCAppのルーティング設定
   */
  angular.module('todomvcApp').config(function($routeProvider) {
    return $routeProvider.when('/angular-todo', {
      templateUrl: 'views/todo.html'
    }).otherwise({
      redirectTo: '/angular-todo'
    });
  });

}).call(this);

//# sourceMappingURL=route.js.map
