// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';

  /*
   * @ngdoc overview
   * @name todomvcApp
   * @description
   * # todomvcApp
   *
   * TodoMVCAppのエントリーポイント
   */
  angular.module('todomvcApp').run(function() {});

}).call(this);

//# sourceMappingURL=run.js.map
