// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';

  /*
   * @ngdoc overview
   * @name todomvcApp
   * @description
   * # todomvcApp
   *
   * TodoMVCAppで利用するモジュールの設定
   */
  angular.module('todomvcApp', ['ngAnimate', 'ngCookies', 'ngMessages', 'ngResource', 'ngRoute', 'ngSanitize', 'ngTouch']);

}).call(this);

//# sourceMappingURL=app.js.map
