// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';

  /*
   * @ngdoc overview
   * @name todomvcApp
   * @description
   * # todomvcApp
   *
   * Main module of the application.
   */
  angular.module('todomvcApp', ['ngAnimate', 'ngCookies', 'ngMessages', 'ngResource', 'ngRoute', 'ngSanitize', 'ngTouch']).config(function($routeProvider) {
    return $routeProvider.when('/', {
      templateUrl: 'views/main.html',
      controller: 'MainCtrl'
    }).otherwise({
      redirectTo: '/'
    });
  });

}).call(this);

//# sourceMappingURL=app.js.map
