// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';

  /**
    * @ngdoc directive
    * @name todomvcApp.directive:ssTodoList
    * @description
    * # Todo一覧表示用のディレクティブ
   */
  angular.module('todomvcApp').controller('todoListCtrl', function(todoService) {
    var vm;
    vm = this;
    vm.todosFilter = "";
    return vm.todos = todoService.todos;
  }).directive('ssTodoList', function() {
    return {
      template: '<div class="todo-form-wrapper" ng-controller="todoListCtrl as vm">\n  <div class="todo-form">\n    <ss-todo-list-input todos="vm.todos"></ss-todo-list-input>\n    <ss-todo-list-item todos-filter="vm.todosFilter" todos="vm.todos"></ss-todo-list-item>\n    <ss-todo-list-footer todos-filter="vm.todosFilter" todos="vm.todos"></ss-todo-list-footer>\n  </div>\n</div>',
      restrict: 'E',
      scope: true,
      replace: true
    };
  });

}).call(this);

//# sourceMappingURL=ssTodoList.js.map
