// Generated by CoffeeScript 1.9.0
(function() {
  angular.module('todomvcApp').directive('ssTodoListFooter', function() {
    return {
      templateUrl: 'views/directives/ssTodoListFooter.html',
      scope: {
        todosFilter: '=',
        todos: '='
      },
      replace: false,
      controller: function($scope, todoService) {
        $scope.getCompleted = todoService.getCompleted;
        $scope.getNotCompleted = todoService.getNotCompleted;
        return $scope.clearCompleted = function() {
          todoService.clearCompleted();
          return $scope.todos = todoService.todos;
        };
      },
      restrict: 'E',
      link: function(scope, element, attrs) {}
    };
  });

}).call(this);

//# sourceMappingURL=ssTodoListFooter.js.map
