// Generated by CoffeeScript 1.9.0
(function() {
  angular.module('todomvcApp').directive('ssTodoListItem', function() {
    return {
      templateUrl: 'views/directives/ssTodoListItem.html',
      scope: {
        todosFilter: '=',
        todos: '='
      },
      replace: false,
      controller: function($scope, todoService) {
        $scope.removeTodo = function(todo) {
          todoService.removeTodo(todo);
          return $scope.todos = todoService.todos;
        };
        $scope.hoverIn = function(todo) {
          return todo.hover = true;
        };
        $scope.hoverOut = function(todo) {
          return todo.hover = false;
        };
        $scope.getFilter = function() {
          var filter;
          filter = {};
          switch ($scope.todosFilter) {
            case 'completed':
              filter = {
                isCompleted: true
              };
              break;
            case 'notCompleted':
              filter = {
                isCompleted: false
              };
          }
          return filter;
        };
        return $scope.onKeyPress = function(keyCode, todo) {
          if (keyCode && todo) {
            switch (keyCode) {
              case 13:
                return todo.endEdit();
              case 27:
                return todo.endEdit(true);
            }
          }
        };
      },
      restrict: 'E'
    };
  });

}).call(this);

//# sourceMappingURL=ssTodoListItem.js.map
