// Generated by CoffeeScript 1.9.0
(function() {
  angular.module('todomvcApp').directive('ssTodoListInput', function() {
    return {
      templateUrl: 'views/directives/ssTodoListInput.html',
      scope: {
        todos: '='
      },
      replace: false,
      controller: function($scope, todoService) {
        $scope.task = "";
        $scope.isBlank = s.isBlank;
        $scope.addTodo = function(task) {
          if (task == null) {
            task = "";
          }
          if (!(s.isBlank(task))) {
            todoService.addTodo(task);
            return $scope.task = "";
          }
        };
        $scope.onKeyPress = function(keyCode) {
          switch (keyCode) {
            case 13:
              return $scope.addTodo($scope.task);
            case 27:
              return $scope.task = "";
          }
        };
        $scope.isAllCompleted = todoService.isAllCompleted;
        $scope.toggleAllCompleted = todoService.toggleAllCompleted;
        return $scope.asAllCompleted = todoService.asAllCompleted;
      },
      restrict: 'E'
    };
  });

}).call(this);

//# sourceMappingURL=ssTodoListInput.js.map
