// Generated by CoffeeScript 1.9.0
(function() {
  angular.module('todomvcApp').directive('ssTodoListItem', function() {
    return {
      template: '<div class="todo-list-item" ng-mouseover="hoverIn(todo)" ng-mouseleave="hoverOut(todo)" ng-repeat="todo in todos | filter:getFilter()">\n  <span class="todo-form-check" ng-class="{\'is-completed\': todo.isCompleted}" ng-click="todo.toggleCompleted()">✓</span>\n  <div class="todo-form-leftbar-short"></div>\n  <span class="todo-form-remove pull-right" ng-click="removeTodo(todo)" ng-show="todo.hover">×</span>\n  <div ng-switch="todo.editable">\n    <div ng-switch-when="true">\n      <div class="todo-list-task"  ng-class="{\'is-completed\': todo.isCompleted}" ng-bind=""></div>\n      <input class="todo-form-input" ng-keyup="onKeyPress($event.keyCode, todo)" ng-model="todo.task" />\n    </div>\n    <div ng-switch-when="false">\n      <div class="todo-list-task"  ng-class="{\'is-completed\': todo.isCompleted}" ng-bind="todo.task" ng-dblclick="todo.edit()"></div>\n    </div>\n  </div>\n</div>',
      scope: {
        todosFilter: '=',
        todos: '='
      },
      replace: false,
      controller: function($scope, todoService) {
        $scope.removeTodo = function(todo) {
          todoService.removeTodo(todo);
          return $scope.todos = todoService.todos;
        };
        $scope.hoverIn = function(todo) {
          return todo.hover = true;
        };
        $scope.hoverOut = function(todo) {
          return todo.hover = false;
        };
        $scope.getFilter = function() {
          var filter;
          filter = {};
          switch ($scope.todosFilter) {
            case 'completed':
              filter = {
                isCompleted: true
              };
              break;
            case 'notCompleted':
              filter = {
                isCompleted: false
              };
          }
          return filter;
        };
        return $scope.onKeyPress = function(keyCode, todo) {
          if (keyCode && todo) {
            switch (keyCode) {
              case 13:
                return todo.endEdit();
              case 27:
                return todo.endEdit(true);
            }
          }
        };
      },
      restrict: 'E'
    };
  });

}).call(this);

//# sourceMappingURL=ssTodoListItem.js.map
