// Generated by CoffeeScript 1.9.0
(function() {
  angular.module('todomvcApp').directive('ssTodoListInput', function() {
    return {
      template: '<div class="todo-form-input-wrapper">\n  <div class="todo-form-leftbar"></div>\n  <div class="todo-form-topbar"></div>\n  <image src="images/down-arrow.png" class="todo-form-down-arrow" ng-class="{\'is-completed\': isAllCompleted()}" ng-click="toggleAllCompleted()" ng-show="todos.length > 0"></image>\n  <input class="todo-form-input" placeholder="What needs to be done?" ng-class="{\'is-blank\': isBlank(task),\'left-spaced\': todos.length == 0}" ng-keyup="onKeyPress($event.keyCode)" ng-model="task" />\n</div>',
      scope: {
        todos: '='
      },
      replace: false,
      controller: function($scope, todoService) {
        $scope.task = "";
        $scope.isBlank = s.isBlank;
        $scope.addTodo = function(task) {
          if (task == null) {
            task = "";
          }
          if (!(s.isBlank(task))) {
            todoService.addTodo(task);
            return $scope.task = "";
          }
        };
        $scope.onKeyPress = function(keyCode) {
          switch (keyCode) {
            case 13:
              return $scope.addTodo($scope.task);
            case 27:
              return $scope.task = "";
          }
        };
        $scope.isAllCompleted = todoService.isAllCompleted;
        $scope.toggleAllCompleted = todoService.toggleAllCompleted;
        return $scope.asAllCompleted = todoService.asAllCompleted;
      },
      restrict: 'E'
    };
  });

}).call(this);

//# sourceMappingURL=ssTodoListInput.js.map
